language: php

php:
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - cp app/config/runtime-conf.xml.dist app/config/runtime-conf.xml
    - bin/bootstrap
    - mysql -uroot -e 'CREATE DATABASE propilex'
    - mysql -uroot propilex < app/config/sql/Propilex.Model.schema.sql
    - npm install -g bower
    - cd web && bower install && cd ..

script:
    - phpunit --coverage-text
    - phantomjs web/js/tests/run-qunit.js file://`pwd`/web/js/tests/index.html
