language: php

php:
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - bin/bootstrap
    - mysql -uroot -e 'CREATE DATABASE propilex'
    - mysql -uroot propilex < app/config/sql/Propilex.Model.schema.sql

script:
    - phpunit --coverage-text
